### PR TITLE
#163220609 Endpoint to rsvp to a specific meetup record

### PR DESCRIPTION
**Pull request by Siffersari**
### What does this PR do ?
This pull request creates an endpoint that allows  a user to respond to a meetup rsvp

- Create an endpoint that allows a user to respond to a meetup rsvp

- Use Postman to test for full functionality

### How should you manually test this?
*Step 1*
 
Navigate to your working directory, create and activate virtual environment 

```$ virtualenv venv```

```$ source venv/bin/activate```

Clone the repository 

```$ git clone https://github.com/Siffersari/Questioner.git```

Install project dependencies

```pip install -r requirements.txt```

*Step 2*
### Running the application
```$ flask run```

### Testing
```$ pytest app/api/tests/v1```

Equivalently, use Postman to test.

### Prerequisites

Pytest, Postman, Git,  Virtualenv

### What are the relevant PT stories?
[A registered user should be able to respond to a meetup RSVP](https://www.pivotaltracker.com/story/show/163220609)

### Screenshots

screenshot from 2019-01-17 08-13-17
screenshot from 2019-01-17 08-12-13
screenshot from 2019-01-17 08-13-26
screenshot from 2019-01-17 08-13-54
screenshot from 2019-01-17 08-14-10

### CODE REVIEW

**Comment by Felix45** [comment]
Your work is good.

**Comment by Siffersari** [comment]
@Felix45  Thank you

**Comment by KelynPNjeri** [comment]
Just add some descriptions to your screenshots other than that. Looks good :+1:

**Comment by Siffersari** [comment]
@KelynPNjeri . Thank you. On it

**Pull request merged**
