### PR TITLE
#162955204 An admin can create meetups

### PR DESCRIPTION
**Pull request by Siffersari**
### What does this PR do?
Creates a UI that an admin user can create meetups

### Description of task to be completed?
* Create & style a page using HTML, CSS & JavaScript that enables an admin user to create meetups
 
### How should you manually test this?
Clone this repository in your working directory on your computer and navigate to Questioner directory
``` 
git clone https://github.com/Siffersari/Questioner.git

cd Questioner/

```
Open **reset.html** on your favorite browser
Open **confirm.html** on your favorite browser

### What are the relevant PT stories?
#162955204 [ An admin user should be able to create meetups](https://www.pivotaltracker.com/story/show/162955204)

### Screenshots

screenshot_2019-01-05 questioner - dashboard 3
screenshot_2019-01-05 questioner - create meetup

this

**Mobile Views**
screenshot_2019-01-05 questioner - dashboard 2
screenshot_2019-01-05 questioner - create meetup 1

### CODE REVIEW

**Comment by tirgei** [comment]
Love the clean design :+1:

**Comment by wachiranduati** [comment]
Thats really nice..
one screenshot is off though....this PR is titled admin can create meetups so the`upcoming meetups` screenshot shouldn't be here....right?

**Comment by Siffersari** [comment]
@wachiranduati I have added another 3rd screenshot on desktop view. If you find time tell me your thoughts. Thanks in advance

**Comment by wachiranduati** [comment]
@Siffersari I get you now.....my bad...it totally makes sense that the admin can also view upcoming meetups....I hadn't thought of it like this...: :+1:

**Comment by Siffersari** [comment]
@wachiranduati Thank you so much for your time. I appreciate

**Pull request merged**
